package nodomain.seven.dip.dotc

object TestC: WithAssertionsDOTC {
    //6.C.1. TEST CASE, THREE ARMY CIRCULAR MOVEMENT

    //6.C.2. TEST CASE, THREE ARMY CIRCULAR MOVEMENT WITH SUPPORT

    //6.C.3. TEST CASE, A DISRUPTED THREE ARMY CIRCULAR MOVEMENT

    //6.C.4. TEST CASE, A CIRCULAR MOVEMENT WITH ATTACKED CONVOY

    //6.C.5. TEST CASE, A DISRUPTED CIRCULAR MOVEMENT DUE TO DISLODGED CONVOY

    //6.C.6. TEST CASE, TWO ARMIES WITH TWO CONVOYS

    //6.C.7. TEST CASE, DISRUPTED UNIT SWAP

    //6.C.8. TEST CASE, NO SELF DISLODGEMENT IN DISRUPTED CIRCULAR MOVEMENT

    //6.C.9. TEST CASE, NO HELP IN DISLODGEMENT OF OWN UNIT IN DISRUPTED CIRCULAR MOVEMENT
}
